# shellcheck shell=bash
# Shared helpers for pre-3.x test scripts. Source only; do not execute.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

log() { printf '[%s] %s\n' "$(ts)" "$*"; }
ok() { log "OK: $*"; }
warn() { log "WARN: $*" >&2; }
fail() { log "FAIL: $*" >&2; exit 1; }
skip() { log "SKIP: $*"; }

# Resolve DEEPSEEK_API_KEY from env or product credentials (never print value).
load_deepseek_key() {
  if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
    return 0
  fi
  local cred="${DEEPSEEK_BUILD_HOME:-$HOME/.deepseek-build}/credentials.json"
  if [[ -f "$cred" ]]; then
    DEEPSEEK_API_KEY="$(
      python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["api_key"])' "$cred" 2>/dev/null || true
    )"
    if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
      export DEEPSEEK_API_KEY
      return 0
    fi
  fi
  return 1
}

find_product_bin() {
  local name="$1"
  local c
  for c in \
    "$ROOT/target/release/$name" \
    "$ROOT/target/debug/$name" \
    "${DEEPSEEK_BUILD_HOME:-$HOME/.deepseek-build}/bin/$name" \
    "${CARGO_HOME:-$HOME/.cargo}/bin/$name"; do
    if [[ -x "$c" ]]; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

find_agent_bin() {
  if [[ -n "${DEEPSEEK_BUILD_AGENT_BIN:-}" && -x "${DEEPSEEK_BUILD_AGENT_BIN}" ]]; then
    echo "$DEEPSEEK_BUILD_AGENT_BIN"
    return 0
  fi
  local c
  for c in \
    "${DEEPSEEK_BUILD_HOME:-$HOME/.deepseek-build}/bin/deepseek-build-agent" \
    "${DEEPSEEK_BUILD_HOME:-$HOME/.deepseek-build}/bin/xai-grok-pager" \
    "$ROOT/third_party/grok-build/target/release/xai-grok-pager" \
    "$ROOT/third_party/grok-build/target/release/xai-grok-pager-bin" \
    "${CARGO_HOME:-$HOME/.cargo}/bin/deepseek-build-agent" \
    "${CARGO_HOME:-$HOME/.cargo}/bin/xai-grok-pager"; do
    if [[ -x "$c" ]]; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

# Write a hermetic GROK_HOME with DeepSeek models (base_url set). Prints path.
make_hermetic_grok_home() {
  local dir
  dir="$(mktemp -d "${TMPDIR:-/tmp}/dsb-pre3x-home.XXXXXX")"
  cat >"$dir/config.toml" <<EOF
# Hermetic DeepSeek Build agent config for pre-3.x live tests.
# Generated by scripts; safe to delete with the temp home.

[models]
default = "deepseek-v4-flash"

[model.deepseek-v4-flash]
model = "deepseek-v4-flash"
name = "DeepSeek V4 Flash"
context_window = 128000
api_backend = "chat_completions"
base_url = "https://api.deepseek.com"
env_key = "DEEPSEEK_API_KEY"

[model.deepseek-v4-pro]
model = "deepseek-v4-pro"
name = "DeepSeek V4 Pro"
context_window = 128000
api_backend = "chat_completions"
base_url = "https://api.deepseek.com"
env_key = "DEEPSEEK_API_KEY"

[endpoints]
xai_api_base_url = "https://api.deepseek.com"

[ui]
theme = "deepseeknight"
# Spec 90 product default — not YOLO-only (G005)
yolo = false
EOF
  chmod 600 "$dir/config.toml"
  echo "$dir"
}

# Redact common secret-like tokens from a log stream (best-effort).
redact_stream() {
  # sk-… keys, bearer tails
  sed -E \
    -e 's/sk-[A-Za-z0-9]{10,}/sk-REDACTED/g' \
    -e 's/(api_key[[:space:]]*=[[:space:]]*")[^"]+"/\1REDACTED"/g' \
    -e 's/(Bearer[[:space:]]+)[A-Za-z0-9._-]{8,}/\1REDACTED/g'
}

record_result() {
  # record_result RESULTS_FILE ID STATUS NOTE
  local file="$1" id="$2" status="$3" note="${4:-}"
  printf '%s\t%s\t%s\n' "$id" "$status" "$note" >>"$file"
}
